CRUD Contract
phuochungus/HomeLand_Apartment_Management_BE pull request #42
Opened 2023-10-29 10:21 UTC by ManhHoDinh

2023-10-29 10:49 UTC, phuochungus requested changes
format code pls
chưa có xử lý upload ảnh hợp đồng

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.controller.ts
-thiếu bảo mật endpoint
-thiếu tài liệu swagger

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.controller.ts
> +        return this.contractService.remove(+id);
id là string nhưng sao truyền tham số lại là number

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.controller.ts
> +        return this.contractService.update(+id, updateContractDto);
id là string nhưng truyền tham số là number

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.controller.ts
> +        return this.contractService.findOne(+id);
lỗi id tương tự

2023-10-29 10:49 UTC, phuochungus commented on src/contract/dto/create-contract.dto.ts
format code pls

2023-10-29 10:49 UTC, phuochungus commented on src/contract/dto/create-contract.dto.ts
> +    expire_at: Date;
field này trong entity là nullable mà sao ở create dto lạ là bắt buộc, xem lại field này có bắt buộc hay ko

2023-10-29 10:49 UTC, phuochungus commented on src/contract/dto/update-contract.dto.ts
> +export class UpdateContractDto extends OmitType(CreateContractDto, [
không xài OmitType cho update dto, xài PartialType

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.service.ts
> +        return this.contractRepository.save(createContract);
không có xử lý upload ảnh à?

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.service.ts
> +    findAll() {
không có async/await

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.service.ts
> +    create(createContract: CreateContractDto) {
không có async/await

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.service.ts
> +        return this.contractRepository.delete({ contract_id: id.toString() });
xem xét lại có nên delete hợp đồng trong db hay ko, nếu có xóa thì phải xem xét khi nào delete và khi nào soft delete

2023-10-29 10:49 UTC, phuochungus commented on src/contract/contract.service.ts
> +    remove(id: number) {
không có async/await

2023-10-29 10:49 UTC, phuochungus commented on src/contract/entities/contract.entity.ts
> +    expire_at: Date;
format code pls

2023-10-29 11:26 UTC, ManhHoDinh commented on src/contract/contract.controller.ts
done

2023-10-29 11:28 UTC, ManhHoDinh commented on src/contract/contract.service.ts
> +        return this.contractRepository.delete({ contract_id: id.toString() });
sua sort

2023-10-29 11:38 UTC, phuochungus requested changes

2023-10-29 11:38 UTC, phuochungus commented on src/contract/contract.controller.ts
> +@Auth()
dùng Auth là allow access cho mọi role, cần giới hạn lại
@Auth(PersonRole.ADMIN, v.v)
yêu cầu tham khảo cách dùng @Auth trong source code

2023-10-29 11:38 UTC, phuochungus commented on src/contract/dto/create-contract.dto.ts
vẫn chưa format code, các dòng dính với nhau nhưng sao dòng cuối lại có dấu cách giữa 2 decorator,
code dính với nhau rất khó đọc

2023-10-29 11:38 UTC, phuochungus commented on src/contract/entities/contract.entity.ts
> +    expire_at: Date;
lỗi format code tương tự

2023-10-30 04:44 UTC, ManhHoDinh commented on src/contract/entities/contract.entity.ts
> +    expire_at: Date;
Là sao?

2023-10-30 04:44 UTC, ManhHoDinh commented on src/contract/contract.controller.ts
> +@Auth()
Đã chỉnh

2023-10-30 04:45 UTC, ManhHoDinh commented
Đã sửa

2023-10-30 06:18 UTC, phuochungus requested changes

2023-10-30 06:18 UTC, phuochungus commented on src/contract/contract.service.ts
> +        } catch (error) {
thiếu login thu hồi ảnh đã dc upload khi có lỗi xay ra do typeorm không thể save

2023-10-30 06:18 UTC, phuochungus commented on src/contract/entities/contract.entity.ts
> +    expire_at: Date;
xem lại trong create dto field này là bắt buộc nhưng trong này là nullable, cần nhất quán logic, nếu hợp đồng nào cũng có expire_at thì sửa trong file này, còn ko thì sửa trong create dto là IsOptional

2023-10-30 06:18 UTC, phuochungus commented on src/contract/dto/update-contract.dto.ts
t chưa hiểu lắm là update contract là update những field nào?

2023-10-30 06:18 UTC, phuochungus commented on src/contract/dto/create-contract.dto.ts
> +    @MaxFileSize(10e6, { each: true })
ở đây chỉ có 1 element nên ko cần dùng each đâu

2023-10-30 06:18 UTC, phuochungus commented on src/contract/dto/create-contract.dto.ts
> +export class CreateContractDto extends PickType(Contract, [] as const) {
suggestion: nên bỏ picktype do ko thấy pick field nào cả (array rỗng [])

2023-10-30 08:12 UTC, ManhHoDinh commented on src/contract/dto/update-contract.dto.ts
chạy swagger test nha

2023-10-30 08:28 UTC, phuochungus approved these changes

2023-10-30 08:40 UTC, merged