Daiduong
phuochungus/HomeLand_Apartment_Management_BE pull request #47
Opened 2023-10-31 08:57 UTC by Daiduong1593572468

PR

2023-10-31 09:52 UTC, phuochungus commented
employee không cần phải bắt buộc nhập emai, cũng ko bắt buộc phải có avatar
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/f06569cf-8d1f-4ecb-905f-5c92f33795a3)
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/c4f09e5c-1b2e-4c5c-98dd-4d3fd7f01de7)

2023-10-31 10:18 UTC, phuochungus requested changes
employee thì email và avatar là ko bắt buộc, email thì có thể có hoặc ko (tùy vào sau này mình có làm chức năng liên quan tới thông báo cho employee qua mail hay ko), còn avatar thì ko cần lưu do employee sẽ ko có quyền dùng hệ thống của mình

2023-11-01 14:47 UTC, Daiduong1593572468 commented
đã fix

2023-11-02 10:26 UTC, phuochungus commented
Cái PATCH nên là form data trên swagger để dễ test được upload ảnh

2023-11-02 14:10 UTC, Daiduong1593572468 commented
Đã fix
Ủa mà cái tạo data bằng seed/start kiểu gì vậy

2023-11-02 20:11 UTC, phuochungus commented
> Đã fix Ủa mà cái tạo data bằng seed/start kiểu gì vậy

là viết logic để insert data hàng loạt vào trong db mà ko cần làm thủ công, vô startSeeding để tham khảo

2023-11-03 02:50 UTC, Daiduong1593572468 commented
ok đã hiểu

2023-11-03 08:33 UTC, phuochungus approved these changes

2023-11-03 09:01 UTC, phuochungus commented
trong PATCH thì tất cả field nên là optional, có 2 field đang là required
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/30723ac6-9f6f-4128-a4fa-838f8a53b547)

2023-11-03 11:01 UTC, Daiduong1593572468 commented
đã fix

2023-11-04 05:22 UTC, phuochungus requested changes
PATCH bị bug khi chỉ truyền 1 field

2023-11-04 05:24 UTC, phuochungus commented
PATCH bị bug khi chỉ truyền 1 field, các field còn lại để trống
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/48d8f671-30a3-463f-bf77-4a212a51f147)
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/212d4c3a-63e1-410b-a8b3-f38c2dabdca8)

2023-11-04 05:26 UTC, phuochungus commented
Chưa có implement hàm thêm data ảo cho Employee, nên viết sớm để lúc test không phải nhập thủ công

2023-11-04 11:26 UTC, Daiduong1593572468 commented
đã fix

2023-11-05 03:22 UTC, phuochungus commented
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/f227f4b3-de71-4d9a-98c7-cd22b08a3de5)
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/52345288-74e1-411e-b473-77233db4cac8)
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/d496a798-b505-4bf7-adef-983de9bbcfe6)

2023-11-06 06:55 UTC, Daiduong1593572468 commented
đã fix

2023-11-06 07:14 UTC, phuochungus requested changes
vẫn còn  lỗi ở PATCH: sửa front image nhưng ko có thay đổi khi GET 
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/86118b20-3342-4cbe-adc8-032d07e41d50)
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/bc826ebc-a6a3-4c42-938a-63b8c928810f)

2023-11-06 10:35 UTC, phuochungus approved these changes

2023-11-06 11:49 UTC, merged