api resident + buillding
phuochungus/HomeLand_Apartment_Management_BE pull request #52
Opened 2023-11-01 01:28 UTC by vocongbinh

2023-11-01 01:29 UTC, vocongbinh commented
chuyển qua cái này đi cái kia nó để lỗi nhìn khó chịu

2023-11-01 07:37 UTC, phuochungus commented
> chuyển qua cái này đi cái kia nó để lỗi nhìn khó chịu
vậy thì sửa như comment trong pr cũ đi

2023-11-01 07:39 UTC, phuochungus requested changes
đọc lại comment bên PR cũ

2023-11-01 07:39 UTC, phuochungus commented on .eslintrc.js
sao file này phải thêm dòng đó vô?

2023-11-01 13:46 UTC, phuochungus commented
Có lỗi phát sinh là do cái này t ràng buộc trong account.entity.ts là để tránh trường hợp account đã tạo ra nhưng ko có person nào liên kết
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/53fce2b8-5fec-44f0-a4a2-fe04ff3c686f)
Có 2 hướng giải quyết:
- Khi tạo account thì phải gán cái person đó vào account.resident account.admin account.technician v.v   trước khi gọi .save()
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/204eecdb-abf1-41a2-bed9-845b22be1a94)
- Xóa cái ràng buộc t đặt trong code account.entity.ts
![image](https://github.com/phuochungus/HomeLand_Apartment_Management_BE/assets/111514441/8f49f0b5-eb91-4429-80e2-452091b8859b)

2023-11-01 13:49 UTC, phuochungus requested changes
cần xem lại và fix theo 1 trong 2 hướng t đề ra

2023-11-02 02:51 UTC, ManhHoDinh commented on .eslintrc.js
ủa sao ta không thấy tin nhắn rep của Bình vậy

2023-11-02 02:59 UTC, ManhHoDinh commented on .eslintrc.js
a

2023-11-02 03:02 UTC, vocongbinh commented
alo

2023-11-02 03:23 UTC, phuochungus approved these changes

2023-11-02 03:23 UTC, merged